const initialState = [
    {
        id: 1,
        img: "https://cdn.pixabay.com/photo/2016/03/27/20/12/desk-1284085__480.jpg",
        author_img: "https://images.pexels.com/photos/997217/pexels-photo-997217.jpeg?auto=compress&cs=tinysrgb&w=600",
        catagory: "computer",
        author: "Arif",
        title: "How to use search engine optimization to drive sales.",
        time: "26 min read",
        date: new Date().toDateString(),
    },
    {
        id: 2,
        img: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Y29tcHV0ZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60",
        author_img:
            "https://raw.githubusercontent.com/Learn-with-Sumit/think-in-a-redux-way/8f0d972d3ba07b8c7952074dcf2fed283f49def8/html_template/assets/lws.svg",
        catagory: "Learner",
        author: "Sumit Saha",
        title: "How to write a Program ! Hello World",
        time: "6 min read",
        date: new Date().toDateString(),
    },
    {
        id: 7,
        img: "https://cdn.pixabay.com/photo/2016/03/27/18/54/technology-1283624__480.jpg",
        author_img: "https://images.pexels.com/photos/997217/pexels-photo-997217.jpeg?auto=compress&cs=tinysrgb&w=600",
        catagory: "Article",
        author: "Sagor Hasan",
        title: "How to write a Program ! Hello World",
        time: "6 min read",
        date: new Date().toDateString(),
    },
    {
        id: 4,
        img: "https://cdn.pixabay.com/photo/2016/04/04/14/12/monitor-1307227__480.jpg",
        author_img:
            "https://raw.githubusercontent.com/Learn-with-Sumit/think-in-a-redux-way/8f0d972d3ba07b8c7952074dcf2fed283f49def8/html_template/assets/lws.svg",
        catagory: "Learner",
        author: "Sumit Saha",
        title: "Improve Your Customer Experience",
        time: "6 min read",
        date: new Date().toDateString(),
    },
    {
        id: 5,
        img: "https://cdn.pixabay.com/photo/2015/01/02/10/47/search-engine-optimization-586422__480.jpg",
        author_img: "https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=600",
        catagory: "Learner",
        author: "Alex Jhon",
        title: "Create a diagram and Make Sure How to Optimize Search Engine Optimazation.",
        time: "6 min read",
        date: new Date().toDateString(),
    },

    {
        id: 6,
        img: "https://cdn.pixabay.com/photo/2016/04/19/05/07/turntable-1337986__480.jpg",
        author_img: "https://images.pexels.com/photos/977796/pexels-photo-977796.jpeg?auto=compress&cs=tinysrgb&w=600",
        catagory: "Computer Expart",
        author: "Jhon Dho",
        title: "How to use search engine optimization to drive sales.",
        time: "6 min read",
        date: new Date().toDateString(),
    },

    {
        id: 7,
        img: "https://images.unsplash.com/photo-1548092372-0d1bd40894a3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fGNvbXB1dGVyfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=600&q=60",
        author_img:
            "https://raw.githubusercontent.com/Learn-with-Sumit/think-in-a-redux-way/8f0d972d3ba07b8c7952074dcf2fed283f49def8/html_template/assets/lws.svg",
        catagory: "Article",
        author: "Sumit Saha",
        title: "How to use search engine optimization to drive sales.",
        time: "05 min read",
        date: new Date().toDateString(),
    },
    {
        id: 8,
        img: "https://cdn.pixabay.com/photo/2016/11/29/06/18/home-office-1867761__480.jpg",
        author_img: "https://images.pexels.com/photos/997217/pexels-photo-997217.jpeg?auto=compress&cs=tinysrgb&w=600",
        catagory: "computer",
        author: "Arif",
        title: "How to use search engine optimization to drive sales.",
        time: "6 min read",
        date: new Date().toDateString(),
    },
    {
        id: 9,
        img: "https://cdn.pixabay.com/photo/2017/01/14/10/56/people-1979261__480.jpg",
        author_img: "https://images.pexels.com/photos/997217/pexels-photo-997217.jpeg?auto=compress&cs=tinysrgb&w=600",
        catagory: "computer",
        author: "Arif",
        title: "How to use search engine optimization to drive sales.",
        time: "34 min read",
        date: new Date().toDateString(),
    },
    {
        id: 10,
        img: "https://cdn.pixabay.com/photo/2017/08/01/00/38/man-2562325__480.jpg",
        author_img: "https://images.pexels.com/photos/997217/pexels-photo-997217.jpeg?auto=compress&cs=tinysrgb&w=600",
        catagory: "Article",
        author: "Sagor Hasan",
        title: "How to write a Program ! Hello World",
        time: "41 min read",
        date: new Date().toDateString(),
    },
    {
        id: 11,
        img: "https://cdn.pixabay.com/photo/2015/01/08/18/30/man-593372__480.jpg",
        author_img: "https://images.pexels.com/photos/977796/pexels-photo-977796.jpeg?auto=compress&cs=tinysrgb&w=600",
        catagory: "Computer Expart",
        author: "Jhon Dho",
        title: "Improve Your Customer Experience",
        time: "16 min read",
        date: new Date().toDateString(),
    },
    {
        id: 12,
        img: "https://cdn.pixabay.com/photo/2020/10/21/18/07/laptop-5673901__480.jpg",
        author_img: "https://images.pexels.com/photos/977796/pexels-photo-977796.jpeg?auto=compress&cs=tinysrgb&w=600",
        catagory: "A Freelancher",
        author: "Jhon Dho",
        title: "How to setup a Computer by HDMI Cable",
        time: "47 min read",
        date: new Date().toDateString(),
    },

    {
        id: 13,
        img: "https://cdn.pixabay.com/photo/2016/11/19/14/00/code-1839406__480.jpg",
        author_img: "https://images.pexels.com/photos/997217/pexels-photo-997217.jpeg?auto=compress&cs=tinysrgb&w=600",
        catagory: "computer",
        author: "Arif",
        title: "How to use search engine optimization to drive sales.",

        time: "23 min read",
        date: new Date().toDateString(),
    },
    {
        id: 14,
        img: "https://cdn.pixabay.com/photo/2016/11/18/12/55/office-1834294__480.jpg",
        author_img: "https://images.pexels.com/photos/977796/pexels-photo-977796.jpeg?auto=compress&cs=tinysrgb&w=600",
        catagory: "Computer Expart",
        author: "Jhon Dho",
        title: "How to setup a Computer by HDMI Cable",
        time: "52 min read",
        date: new Date().toDateString(),
    },
    {
        id: 15,
        img: "https://cdn.pixabay.com/photo/2017/06/23/11/49/laptop-2434393__480.jpg",
        author_img: "https://images.pexels.com/photos/977796/pexels-photo-977796.jpeg?auto=compress&cs=tinysrgb&w=600",
        catagory: "Computer Expart",
        author: "Jhon Dho",
        title: "Improve Your Customer Experience",
        time: "15 min read",
        date: new Date().toDateString(),
    },

    {
        id: 16,
        img: "https://cdn.pixabay.com/photo/2015/01/08/18/27/startup-593341__480.jpg",
        author_img:
            "https://raw.githubusercontent.com/Learn-with-Sumit/think-in-a-redux-way/8f0d972d3ba07b8c7952074dcf2fed283f49def8/html_template/assets/lws.svg",
        catagory: "Learner",
        author: "Sumit Saha",
        title: "How to write a Program ! Hello World",
        time: "6 min read",
        date: new Date().toDateString(),
    },

    {
        id: 16,
        img: "https://cdn.pixabay.com/photo/2015/01/08/18/27/startup-593341__480.jpg",
        author_img: "https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=600",
        catagory: "Learner",
        author: "Alex Jhon",
        title: "How to write a Program ! Hello World",
        time: "6 min read",
        date: new Date().toDateString(),
    },
];
export default initialState;
